name: Scheduled GET Request

on:
  schedule:
    - cron: "0,25,50 7-18 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make a GET request
        run: |
          curl -X GET "https://backendb4a-heau1v79.b4a.run/cadastros/keep-alive"
